### ISSUE TITLE
canvacord.rank() not a function

### ISSUE THREAD

**Issue by Cyanic76** [Snowflake107/canvacord#14]
Hello,

I'm trying to use the .rank() image generator like this 
```js
const cc = require("canvacord")
const cv = new cc.Canvas();
const output = await dl.Fetch(p.id) // dl = require("discord-leveling");
const neededxp = 10 * (output.level^2) + 100 * output.level + 100
  
// p.username, p.discriminator, output.level, neededxp, output.xp, p.avatarURL({format: "jpg", size: 1024})
let trigger = await cv.rank({
  username: p.username,
  discrim: p.discriminator,
  level: output.level,
  neededXP: neededxp,
  currentXP: output.xp,
  avatarURL: p.avatarURL({format: "jpg", size: 1024})
});
```

But it is giving this error: `cv.rank is not a function`. I'm also using canvacord **2.0.2**.

How can I fix this? Thanks for your help.

**Comment by Snowflake107** [comment]
@Cyanic76 are you sure you have the latest version?

**Comment by Cyanic76** [comment]
I've double-checked it:
```json
"canvacord": "^2.0.2",
```

**Comment by Snowflake107** [comment]
Can you try `npm ls canvacord`?

**Comment by Cyanic76** [comment]
Sure : `npm ERR! invalid: canvacord@1.0.1 /app/node_modules/canvacord`

**Comment by Snowflake107** [comment]
Close by mistake 😅
Can you try **deleting** the `node_modules` folder and reinstalling the packages? @Cyanic76

**Comment by Cyanic76** [comment]
The `is not a function` error is solved! Thanks a ton!

**Comment by ImagineGamingPlay123** [comment]
Add more images
