### ISSUE TITLE
canvacord.welcomer() is not a function

### ISSUE THREAD

**Issue by AwesomeStickz** [Snowflake107/canvacord#17]
I'm not sure whether you wanted it to be a welcome method or welcomer method, but this line in the code says it's a welcome method while readme says it's welcomer. 

File - scr/Canvas.js
Line number - 531 
Code: 

```
async welcome({ username, discrim, avatarURL }) {
```

**Comment by Snowflake107** [comment]
You can use `welcome()` for now. It was a mistake on the documentation. `welcomer()` is available on the development branch and will be published soon. **[Canvacord.welcomer()](https://github.com/Snowflake107/canvacord/blob/ea2797065121b10d02321d4f4fc857c7948440fc/src/Canvas.js#L583)**
