### ISSUE TITLE
const canva = new Canvacord(); returns an error

### ISSUE THREAD

**Issue by cyanicB** [Snowflake107/canvacord#18]
Hello,

Since I updated my bot to canvacord 3.0.4, there's this error popping up in my console:
`TypeError: cc.Canvacord is not a constructor`
Note that `cc` is defined by `require("canvacord")`.
I've followed what the doc says but yeah it still appears.

Is there a fix in version 3.0.4 or is it just me doing the wrong thing? Thanks for your help.

**Comment by Snowflake107** [comment]
just do `new cc()`

**Comment by cyanicB** [comment]
Worked (as you would expect)
In what version have you changed how it works?
