### ISSUE TITLE
Lots of bugs?

### ISSUE THREAD

**Issue by TH3-UNKNOWN** [Snowflake107/canvacord#23]
Takes forever to load 
![image](https://user-images.githubusercontent.com/48633565/89355286-06225b80-d689-11ea-850e-840b3b56fbfd.png)

**AND**

TEXT IS BAD
https://cdn.discordapp.com/attachments/706709621783527494/740340812239470622/file.png
![image](https://user-images.githubusercontent.com/48633565/89355331-1cc8b280-d689-11ea-8797-2689b47f3fbf.png)

**Comment by TH3-UNKNOWN** [comment]
NVM the text is bad, I just made a mistake lol

**Comment by TheGamer456YT** [comment]
You corrected yourself... so then close the issue lol
